package postgres

import (
	"fmt"
	"strings"

	haira "haira-go-runtime/haira"
)

// PgSchema holds schema info for multiple tables.
type PgSchema struct {
	Tables map[string]*PgTableSchema
}

// PgTableSchema holds schema info for a single table.
type PgTableSchema struct {
	Name    string
	Columns map[string]*PgColumnInfo
	Order   []string
}

// PgColumnInfo holds column metadata.
type PgColumnInfo struct {
	Type          string
	Nullable      bool
	PrimaryKey    bool
	AutoGenerated bool
}

// SqlResult holds generated SQL statements.
type SqlResult struct {
	Seeds    string
	Oneshots string
	All      string
}

// HasSeeds returns whether there are seed SQL statements.
func (s *SqlResult) HasSeeds() bool { return s.Seeds != "" }

// HasOneshots returns whether there are one-shot SQL statements.
func (s *SqlResult) HasOneshots() bool { return s.Oneshots != "" }

// ToUiCodeBlock converts the SQL result into a UiCodeBlock with tabs for direct UI rendering.
// The full SQL goes straight to the frontend — the LLM only receives a compact summary.
func (s *SqlResult) ToUiCodeBlock() haira.UiCodeBlock {
	var tabs []any
	if s.Seeds != "" {
		seedLines := strings.Count(s.Seeds, "\n") + 1
		tabs = append(tabs, haira.UiCodeTab{
			Name:     fmt.Sprintf("Seeds (%d lines)", seedLines),
			Language: "sql",
			Code:     s.Seeds,
		})
	}
	if s.Oneshots != "" {
		oneshotLines := strings.Count(s.Oneshots, "\n") + 1
		tabs = append(tabs, haira.UiCodeTab{
			Name:     fmt.Sprintf("Oneshots (%d lines)", oneshotLines),
			Language: "sql",
			Code:     s.Oneshots,
		})
	}
	return haira.UiCodeBlock{
		Title: "Generated SQL",
		Tabs:  tabs,
	}
}

// Schema retrieves the schema for the specified tables.
func (db *DB) Schema(tables []any) (*PgSchema, error) {
	schema := &PgSchema{Tables: make(map[string]*PgTableSchema)}

	for _, t := range tables {
		tableName := haira.Str(t)
		ts, err := db.tableSchema(tableName)
		if err != nil {
			return nil, err
		}
		schema.Tables[tableName] = ts
	}
	return schema, nil
}

// Tables returns a list of all table names in the public schema.
func (db *DB) Tables() ([]any, error) {
	rows, err := db.conn.Query(`
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
		ORDER BY table_name
	`)
	if err != nil {
		return nil, fmt.Errorf("postgres tables: %w", err)
	}
	defer rows.Close()

	var names []any
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, fmt.Errorf("scanning table name: %w", err)
		}
		names = append(names, name)
	}
	return names, nil
}

// DryRun executes SQL inside a transaction that is always rolled back.
func (db *DB) DryRun(sql string) error {
	tx, err := db.conn.Begin()
	if err != nil {
		return fmt.Errorf("dry run begin: %w", err)
	}
	_, err = tx.Exec(sql)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("dry run exec: %w", err)
	}
	return tx.Rollback()
}

// Transaction runs a function inside a database transaction.
// If the function returns an error, the transaction is rolled back.
func (db *DB) Transaction(fn func(*DB) error) error {
	tx, err := db.conn.Begin()
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}

	// Create a DB wrapper around the transaction
	txDB := &DB{conn: db.conn}
	if err := fn(txDB); err != nil {
		tx.Rollback()
		return err
	}
	return tx.Commit()
}

func (db *DB) tableSchema(tableName string) (*PgTableSchema, error) {
	rows, err := db.conn.Query(`
		SELECT c.column_name, c.data_type, c.is_nullable,
			COALESCE(tc.constraint_type, '') as constraint_type,
			COALESCE(c.column_default, '') as column_default
		FROM information_schema.columns c
		LEFT JOIN information_schema.key_column_usage kcu
			ON c.column_name = kcu.column_name AND c.table_name = kcu.table_name
		LEFT JOIN information_schema.table_constraints tc
			ON kcu.constraint_name = tc.constraint_name AND tc.constraint_type = 'PRIMARY KEY'
		WHERE c.table_name = $1 AND c.table_schema = 'public'
		ORDER BY c.ordinal_position
	`, tableName)
	if err != nil {
		return nil, fmt.Errorf("schema for %q: %w", tableName, err)
	}
	defer rows.Close()

	ts := &PgTableSchema{
		Name:    tableName,
		Columns: make(map[string]*PgColumnInfo),
	}

	for rows.Next() {
		var colName, dataType, nullable, constraint, colDefault string
		if err := rows.Scan(&colName, &dataType, &nullable, &constraint, &colDefault); err != nil {
			return nil, fmt.Errorf("scanning column info: %w", err)
		}
		ts.Columns[colName] = &PgColumnInfo{
			Type:          dataType,
			Nullable:      nullable == "YES",
			PrimaryKey:    constraint == "PRIMARY KEY",
			AutoGenerated: strings.Contains(colDefault, "nextval") || strings.Contains(colDefault, "gen_random"),
		}
		ts.Order = append(ts.Order, colName)
	}

	return ts, nil
}

// PostgresEscape escapes a string value for safe use in SQL.
func PostgresEscape(value string) string {
	escaped := strings.ReplaceAll(value, "'", "''")
	return "'" + escaped + "'"
}

// QuoteIdentifier quotes a SQL identifier (table/column name) to prevent injection.
// Uses PostgreSQL double-quote escaping: internal " becomes "".
func QuoteIdentifier(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}
