package postgres

import (
	"errors"
	"fmt"
	"strings"

	"github.com/lib/pq"
	haira "haira-go-runtime/haira"
)

// PgForeignKey holds column-level FK mapping info.
type PgForeignKey struct {
	ChildTable   string
	ChildColumn  string
	ParentTable  string
	ParentColumn string
}

// PgSchema holds schema info for multiple tables.
type PgSchema struct {
	Tables map[string]*PgTableSchema
	// FKDeps maps table name → list of table names it depends on (via FK).
	// Only populated for tables present in Tables.
	FKDeps map[string][]string
	// FKColumns holds column-level FK mappings for cross-table value validation.
	FKColumns []PgForeignKey
}

// PgTableSchema holds schema info for a single table.
type PgTableSchema struct {
	Name         string
	Columns      map[string]*PgColumnInfo
	Order        []string
	UniqueIndexes [][]string // non-PK unique indexes, each entry is a list of column names
}

// PgColumnInfo holds column metadata.
type PgColumnInfo struct {
	Type          string
	Nullable      bool
	PrimaryKey    bool
	AutoGenerated bool // true only for serial/sequence columns (nextval) — excluded from INSERT
	HasDefault    bool // true if column has any DB default — not required in Excel validation
}

// SqlResult holds generated SQL statements.
type SqlResult struct {
	Seeds    string
	Oneshots string
	All      string
}

// HasSeeds returns whether there are seed SQL statements.
func (s *SqlResult) HasSeeds() bool { return s.Seeds != "" }

// HasOneshots returns whether there are one-shot SQL statements.
func (s *SqlResult) HasOneshots() bool { return s.Oneshots != "" }

// ToUiCodeBlock converts the SQL result into a UiCodeBlock with tabs for direct UI rendering.
// The full SQL goes straight to the frontend — the LLM only receives a compact summary.
func (s *SqlResult) ToUiCodeBlock() haira.UiCodeBlock {
	var tabs []any
	if s.Seeds != "" {
		seedLines := strings.Count(s.Seeds, "\n") + 1
		tabs = append(tabs, haira.UiCodeTab{
			Name:     fmt.Sprintf("Seeds (%d lines)", seedLines),
			Language: "sql",
			Code:     s.Seeds,
		})
	}
	if s.Oneshots != "" {
		oneshotLines := strings.Count(s.Oneshots, "\n") + 1
		tabs = append(tabs, haira.UiCodeTab{
			Name:     fmt.Sprintf("Oneshots (%d lines)", oneshotLines),
			Language: "sql",
			Code:     s.Oneshots,
		})
	}
	return haira.UiCodeBlock{
		Title: "Generated SQL",
		Tabs:  tabs,
	}
}

// Schema retrieves the schema for the specified tables, including FK dependencies.
func (db *DB) Schema(tables []any) (*PgSchema, error) {
	if db == nil || db.conn == nil {
		return nil, fmt.Errorf("database not connected")
	}
	schema := &PgSchema{
		Tables: make(map[string]*PgTableSchema),
		FKDeps: make(map[string][]string),
	}

	tableSet := make(map[string]bool)
	for _, t := range tables {
		tableName := haira.Str(t)
		tableSet[tableName] = true
		ts, err := db.tableSchema(tableName)
		if err != nil {
			return nil, err
		}
		schema.Tables[tableName] = ts
	}

	// Query FK dependencies among the requested tables.
	fkRows, err := db.conn.Query(`
		SELECT DISTINCT
			tc.table_name AS child_table,
			ccu.table_name AS parent_table
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
			ON tc.constraint_name = kcu.constraint_name
			AND tc.table_schema = kcu.table_schema
		JOIN information_schema.constraint_column_usage ccu
			ON ccu.constraint_name = tc.constraint_name
		WHERE tc.constraint_type = 'FOREIGN KEY'
			AND tc.table_schema = 'public'
	`)
	if err == nil {
		defer fkRows.Close()
		for fkRows.Next() {
			var child, parent string
			if fkRows.Scan(&child, &parent) == nil && tableSet[child] && tableSet[parent] && child != parent {
				schema.FKDeps[child] = append(schema.FKDeps[child], parent)
			}
		}
	}

	// Query column-level FK mappings for cross-table value validation.
	// Uses pg_constraint for correct multi-column FK support via array_position matching.
	fkColRows, fkColErr := db.conn.Query(`
		SELECT
			c.conrelid::regclass::text AS child_table,
			a1.attname AS child_column,
			c.confrelid::regclass::text AS parent_table,
			a2.attname AS parent_column
		FROM pg_constraint c
		JOIN pg_attribute a1 ON a1.attrelid = c.conrelid AND a1.attnum = ANY(c.conkey)
		JOIN pg_attribute a2 ON a2.attrelid = c.confrelid AND a2.attnum = ANY(c.confkey)
		JOIN pg_namespace n ON n.oid = c.connamespace
		WHERE c.contype = 'f'
			AND n.nspname = 'public'
			AND array_position(c.conkey, a1.attnum) = array_position(c.confkey, a2.attnum)
	`)
	if fkColErr == nil {
		defer fkColRows.Close()
		for fkColRows.Next() {
			var fk PgForeignKey
			if fkColRows.Scan(&fk.ChildTable, &fk.ChildColumn, &fk.ParentTable, &fk.ParentColumn) == nil {
				if tableSet[fk.ChildTable] && tableSet[fk.ParentTable] {
					schema.FKColumns = append(schema.FKColumns, fk)
				}
			}
		}
	}

	return schema, nil
}

// TopoSort returns tableNames sorted so that FK-referenced (parent) tables come first.
// Tables with no FK deps appear first; tables with unresolved deps are appended at the end.
func TopoSort(tableNames []string, fkDeps map[string][]string) []string {
	// Build adjacency: parent → children; compute in-degrees.
	inDeg := make(map[string]int, len(tableNames))
	children := make(map[string][]string, len(tableNames))
	for _, n := range tableNames {
		inDeg[n] = 0
	}
	for _, n := range tableNames {
		for _, dep := range fkDeps[n] {
			if _, known := inDeg[dep]; !known {
				continue // dep not in our set
			}
			children[dep] = append(children[dep], n)
			inDeg[n]++
		}
	}

	// Kahn's algorithm.
	var queue []string
	for _, n := range tableNames {
		if inDeg[n] == 0 {
			queue = append(queue, n)
		}
	}

	sorted := make([]string, 0, len(tableNames))
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		sorted = append(sorted, node)
		for _, child := range children[node] {
			inDeg[child]--
			if inDeg[child] == 0 {
				queue = append(queue, child)
			}
		}
	}

	// Append any remaining nodes (cycles or disconnected).
	seen := make(map[string]bool, len(sorted))
	for _, n := range sorted {
		seen[n] = true
	}
	for _, n := range tableNames {
		if !seen[n] {
			sorted = append(sorted, n)
		}
	}
	return sorted
}

// Tables returns a list of all table names in the public schema.
func (db *DB) Tables() ([]any, error) {
	rows, err := db.conn.Query(`
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
		ORDER BY table_name
	`)
	if err != nil {
		return nil, fmt.Errorf("postgres tables: %w", err)
	}
	defer rows.Close()

	var names []any
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, fmt.Errorf("scanning table name: %w", err)
		}
		names = append(names, name)
	}
	return names, nil
}

// DryRun executes SQL inside a transaction that is always rolled back.
func (db *DB) DryRun(sql string) error {
	tx, err := db.conn.Begin()
	if err != nil {
		return fmt.Errorf("dry run begin: %w", err)
	}
	_, err = tx.Exec(sql)
	if err != nil {
		tx.Rollback()
		return fmt.Errorf("dry run exec: %w", err)
	}
	return tx.Rollback()
}

// DryRunDiagnostic holds structured diagnostics from a dry-run attempt.
type DryRunDiagnostic struct {
	Success    bool
	ErrorType  string // "foreign_key", "unique_constraint", "not_null", "check", "syntax", "connection", "other"
	Constraint string
	Table      string
	Column     string
	Detail     string
	Hint       string
	Suggestion string
	RawError   string
}

// DryRunDiagnose executes SQL inside a rolled-back transaction and returns
// structured diagnostics. Unlike DryRun which returns a plain error,
// this parses PostgreSQL error codes to identify the error type (FK violation,
// unique constraint, NOT NULL, etc.) and provides actionable suggestions.
func (db *DB) DryRunDiagnose(sqlStr string) *DryRunDiagnostic {
	tx, err := db.conn.Begin()
	if err != nil {
		return &DryRunDiagnostic{
			ErrorType:  "connection",
			RawError:   err.Error(),
			Suggestion: "Cannot start transaction — check database connection.",
		}
	}
	_, execErr := tx.Exec(sqlStr)
	tx.Rollback() // always rollback

	if execErr == nil {
		return &DryRunDiagnostic{Success: true}
	}

	diag := &DryRunDiagnostic{RawError: execErr.Error()}

	var pqErr *pq.Error
	if errors.As(execErr, &pqErr) {
		diag.Constraint = pqErr.Constraint
		diag.Table = pqErr.Table
		diag.Column = pqErr.Column
		diag.Detail = pqErr.Detail
		diag.Hint = pqErr.Hint

		switch pqErr.Code.Name() {
		case "foreign_key_violation":
			diag.ErrorType = "foreign_key"
			diag.Suggestion = fmt.Sprintf(
				"A row references a value that doesn't exist in the parent table. "+
					"Add the missing value to the parent table, or remove the referencing row. "+
					"Constraint: %s", pqErr.Constraint)
			if pqErr.Detail != "" {
				diag.Suggestion += "\n" + pqErr.Detail
			}
		case "unique_violation":
			diag.ErrorType = "unique_constraint"
			diag.Suggestion = fmt.Sprintf(
				"Duplicate rows conflict with existing data or with each other in this batch. "+
					"Check for duplicate key values and remove or update them. "+
					"Constraint: %s", pqErr.Constraint)
			if pqErr.Detail != "" {
				diag.Suggestion += "\n" + pqErr.Detail
			}
		case "not_null_violation":
			diag.ErrorType = "not_null"
			diag.Suggestion = fmt.Sprintf(
				"Column %q in table %q cannot be empty — provide a value or set a default in the DB.",
				pqErr.Column, pqErr.Table)
		case "check_violation":
			diag.ErrorType = "check"
			diag.Suggestion = fmt.Sprintf(
				"A value fails a check constraint. Review allowed values for constraint %q.",
				pqErr.Constraint)
		case "syntax_error":
			diag.ErrorType = "syntax"
			diag.Suggestion = "The generated SQL contains a syntax error. This is likely a bug in the SQL generator."
		default:
			diag.ErrorType = "other"
			diag.Suggestion = pqErr.Message
		}
	} else {
		diag.ErrorType = "other"
		diag.Suggestion = execErr.Error()
	}

	return diag
}

// ToUiGroup renders a DryRunDiagnostic as a UiGroup with status card and error details.
func (d *DryRunDiagnostic) ToUiGroup() haira.UiGroup {
	if d.Success {
		return haira.UiGroup{Children: []any{
			haira.UiStatusCard{Status: "success", Title: "Dry-Run Passed", Message: "SQL executed successfully (transaction rolled back)."},
		}}
	}

	typeLabels := map[string]string{
		"foreign_key":       "Foreign Key Violation",
		"unique_constraint": "Unique Constraint Violation",
		"not_null":          "NOT NULL Violation",
		"check":             "Check Constraint Violation",
		"syntax":            "SQL Syntax Error",
		"connection":        "Database Connection Error",
		"other":             "Database Error",
	}
	label := typeLabels[d.ErrorType]
	if label == "" {
		label = "Database Error"
	}

	var children []any
	children = append(children, haira.UiStatusCard{
		Status:  "error",
		Title:   "Dry-Run Failed — " + label,
		Message: d.Suggestion,
	})

	// Key-value error details
	var items []any
	if d.Constraint != "" {
		items = append(items, haira.UiKVItem{Key: "Constraint", Value: d.Constraint})
	}
	if d.Table != "" {
		items = append(items, haira.UiKVItem{Key: "Table", Value: d.Table})
	}
	if d.Column != "" {
		items = append(items, haira.UiKVItem{Key: "Column", Value: d.Column})
	}
	if d.Detail != "" {
		items = append(items, haira.UiKVItem{Key: "Detail", Value: d.Detail})
	}
	if d.Hint != "" {
		items = append(items, haira.UiKVItem{Key: "Hint", Value: d.Hint})
	}
	if d.ErrorType != "" {
		items = append(items, haira.UiKVItem{Key: "Error Code", Value: d.ErrorType})
	}
	if len(items) > 0 {
		children = append(children, haira.UiKeyValue{Title: "Error Details", Items: items})
	}

	return haira.UiGroup{Children: children}
}

// Transaction runs a function inside a database transaction.
// If the function returns an error, the transaction is rolled back.
func (db *DB) Transaction(fn func(*DB) error) error {
	tx, err := db.conn.Begin()
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}

	// Create a DB wrapper around the transaction
	txDB := &DB{conn: db.conn}
	if err := fn(txDB); err != nil {
		tx.Rollback()
		return err
	}
	return tx.Commit()
}

func (db *DB) tableSchema(tableName string) (*PgTableSchema, error) {
	if db == nil || db.conn == nil {
		return nil, fmt.Errorf("database not connected")
	}
	rows, err := db.conn.Query(`
		SELECT
			c.column_name,
			c.data_type,
			c.is_nullable,
			CASE WHEN pk.column_name IS NOT NULL THEN 'PRIMARY KEY' ELSE '' END AS constraint_type,
			COALESCE(c.column_default, '') AS column_default
		FROM information_schema.columns c
		LEFT JOIN (
			SELECT kcu.column_name
			FROM information_schema.key_column_usage kcu
			JOIN information_schema.table_constraints tc
				ON kcu.constraint_name = tc.constraint_name
				AND kcu.table_schema = tc.table_schema
			WHERE tc.constraint_type = 'PRIMARY KEY'
				AND kcu.table_name = $1
				AND kcu.table_schema = 'public'
		) pk ON c.column_name = pk.column_name
		WHERE c.table_name = $1 AND c.table_schema = 'public'
		ORDER BY c.ordinal_position
	`, tableName)
	if err != nil {
		return nil, fmt.Errorf("schema for %q: %w", tableName, err)
	}
	defer rows.Close()

	ts := &PgTableSchema{
		Name:    tableName,
		Columns: make(map[string]*PgColumnInfo),
	}

	for rows.Next() {
		var colName, dataType, nullable, constraint, colDefault string
		if err := rows.Scan(&colName, &dataType, &nullable, &constraint, &colDefault); err != nil {
			return nil, fmt.Errorf("scanning column info: %w", err)
		}
		ts.Columns[colName] = &PgColumnInfo{
			Type:          dataType,
			Nullable:      nullable == "YES",
			PrimaryKey:    constraint == "PRIMARY KEY",
			AutoGenerated: isSerialColumn(colDefault),
			HasDefault:    colDefault != "",
		}
		ts.Order = append(ts.Order, colName)
	}

	// Fetch non-PK unique indexes
	uiRows, err := db.conn.Query(`
		SELECT i.relname AS index_name, a.attname AS column_name
		FROM pg_class t
		JOIN pg_index ix ON t.oid = ix.indrelid
		JOIN pg_class i ON i.oid = ix.indexrelid
		JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(ix.indkey)
		JOIN pg_namespace n ON n.oid = t.relnamespace
		WHERE t.relname = $1
		  AND n.nspname = 'public'
		  AND ix.indisunique = true
		  AND ix.indisprimary = false
		ORDER BY i.relname, array_position(ix.indkey, a.attnum)
	`, tableName)
	if err == nil {
		defer uiRows.Close()
		indexMap := make(map[string][]string)
		var indexOrder []string
		for uiRows.Next() {
			var idxName, colName string
			if uiRows.Scan(&idxName, &colName) == nil {
				if _, seen := indexMap[idxName]; !seen {
					indexOrder = append(indexOrder, idxName)
				}
				indexMap[idxName] = append(indexMap[idxName], colName)
			}
		}
		for _, idxName := range indexOrder {
			ts.UniqueIndexes = append(ts.UniqueIndexes, indexMap[idxName])
		}
	}

	return ts, nil
}

// isSerialColumn returns true for DB-generated PK columns that cannot be
// meaningfully user-provided: serial/sequence columns (nextval) and UUID
// generators (gen_random_uuid, uuid_generate_*). These are excluded from
// INSERT statements so the ON CONFLICT target falls back to the unique index.
// All other defaults (now(), false, '', 0) are user-overridable.
func isSerialColumn(colDefault string) bool {
	d := strings.ToLower(strings.TrimSpace(colDefault))
	return strings.Contains(d, "nextval(") ||
		strings.Contains(d, "gen_random_uuid(") ||
		strings.Contains(d, "uuid_generate_")
}

// PostgresEscape escapes a string value for safe use in SQL.
func PostgresEscape(value string) string {
	escaped := strings.ReplaceAll(value, "'", "''")
	return "'" + escaped + "'"
}

// QuoteIdentifier quotes a SQL identifier (table/column name) to prevent injection.
// Uses PostgreSQL double-quote escaping: internal " becomes "".
func QuoteIdentifier(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}
